
spring.datasource.url=jdbc:mysql://localhost:3306/reservas_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=CaKJ+g6/mQDd0jnwEb0+kZo4K+fd2SST54yO8ETSvZvHX6CMz5e3fawtSODondT4PbgU6rPYiS+ubAw5tLBH8Q==
jwt.expiration=3600000
jwt.inactivity-timeout=600000
